### Test your report endpoint
GET http://localhost:3001/api/report
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNlFXU2hKUk8xYlBSeEhLcExjZTM1cUlKemwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3NjUwMjk2NDAsImZ2YSI6WzczLC0xXSwiaWF0IjoxNzY1MDI5NTgwLCJpc3MiOiJodHRwczovL3NldHRsZWQtYmVhZ2xlLTEuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzY1MDI5NTcwLCJzaWQiOiJzZXNzXzM2VEtYaE0ySzJGZkhmemNJWnBJMTZkbVdmbiIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzZUS1hpQjNpMzVxNnUzS3RpWTdPZ1N0MzdvIiwidiI6Mn0.lA3xVLlMfc9bm2jwj9jiKRzfU2XxJaOfhhBPZVP9omUxiFxdKhHJ_dWRK6pqXG6CmQ6wtcpUcwyc5FmUYYF0HNrJ4ucRgXEgeVTjYcJ1XQzxM_HtLy1WCwtVxGEgTgFPz2S4EfKotM_7MX-uTdSCCPI96mn6J9FFxEV6ULguCQ2gN853rmkXe0pQdKqP3NhU4CJ30SXBpVm3FzbYsg9dsp3caUiyEVbZ-iEMiiehPP8O_4whIWxWisQBu8dR9dsT5x1wjgUjNoPNN52L1H23uSVYk9R9zyqlFknJdSwvMgpMWDWkFHcsC_vEkdq7W2xVcd2KhuVF8aygkMYZnDxGsw
